# Generated by Django 4.0.5 on 2022-06-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(upload_to='news/')),
                ('published_date', models.DateField()),
                ('categories', models.ManyToManyField(to='web.category')),
            ],
        ),
    ]
